const endpoints = {
  EXPLORE_ENDPOINT: '/explore',
  PICKERS_ENDPOINT: '/pickers',
  COUNTRIES_ENDPOINT: '/geo',
  CATEGORIES_ENDPOINT: '/category',
  RELATED_SEARCHES_ENDPOINT: '/widgetdata/relatedsearches',
  RELATED_QUERIES_ENDPOINT: '/widgetdata/relatedqueries',
  DAILY_TRENDS_ENDPOINT: '/dailytrends',
  REALTIME_TRENDS_ENDPOINT: '/realtimetrends',
  INDIVIDUAL_STORY_ENDPOINT: '/stories',
}

export const countries = [
  "China",
  "India",
  "United States",
  "Indonesia",
  "Brazil",
  "Nigeria",
  "Bangladesh",
  "Russia",
  "Pakistan",
  "Japan",
  "Mexico",
  "Iran",
  "Germany",
  "Philippines",
  "Vietnam",
  "United Kingdom",
  "Turkey",
  "France",
  "Egypt",
  "South Korea",
  "Spain",
  "Thailand",
  "Italy",
  "Poland",
  "Canada",
  "Argentina",
  "Central African Republic",
  "Colombia",
  "Saudi Arabia",
  "Georgia",
  "Ukraine",
  "Algeria",
  "Morocco",
  "Taiwan",
  "Australia",
  "Venezuela",
  "Ethiopia",
  "Iraq",
  "Uzbekistan",
  "Albania",
  "Netherlands",
  "Peru",
  "Chile",
  "Kazakhstan",
  "Romania",
  "Sudan",
  "Ghana",
  "Armenia",
  "Uganda",
  "Belgium",
  "Sweden",
  "Ecuador",
  "Tanzania",
  "United Arab Emirates",
  "Kenya",
  "Czech Republic",
  "Switzerland",
  "Greece",
  "Azerbaijan",
  "Austria",
  "Portugal",
  "Yemen",
  "Hungary",
  "Sri Lanka",
  "Belarus",
  "Congo - Brazzaville",
  "Dominica",
  "Guatemala",
  "Israel",
  "Hong Kong",
  "Jordan",
  "Tunisia",
  "Nepal",
  "Syria",
  "Serbia",
  "Mozambique",
  "Cuba",
  "Cameroon",
  "Denmark",
  "Cambodia",
  "Norway",
  "Bolivia",
  "Finland",
  "Singapore",
  "Zambia",
  "Lebanon",
  "Senegal",
  "Bulgaria",
  "Zimbabwe",
  "Slovakia",
  "New Zealand",
  "Angola",
  "Paraguay",
  "Afghanistan",
  "Kuwait",
  "Ireland",
  "Oman",
  "Costa Rica",
  "Palestine",
  "Moldova",
  "Cyprus",
  "Luxembourg"
]

export const realtime_countries = [
  "Germany - DE",
  "Argentina - AR",
  "Australia - AU",
  "Austria - AT",
  "Belgium - BE",
  "Brazil - BR",
  "Canada - CA",
  "Chile - CL",
  "Colombia - CO",
  "Czechia - CZ",
  "Denmark - DK",
  "Egypt - EG",
  "Finland - FI",
  "France - FR",
  "Greece - GR",
  "Hong Kong - HK",
  "Hungary - HU",
  "India - IN",
  "Indonesia - ID",
  "Ireland - IE",
  "Israel - IL",
  "Italy - IT",
  "Japan - JP",
  "Kenya - KE",
  "Malaysia - MY",
  "Mexico - MX",
  "Netherlands - NL",
  "New Zealand - NZ",
  "Nigeria - NG",
  "Norway - NO",
  "Philippines - PH",
  "Poland - PL",
  "Portugal - PT",
  "Romania - RO",
  "Russia - RU",
  "Saudi Arabia - SA",
  "Singapore - SG",
  "South Africa - ZA",
  "South Korea - KR",
  "Sweden - SE",
  "Switzerland - CH",
  "Taiwan - TW",
  "Thailand - TH",
  "Turkey - TR",
  "Ukraine - UA",
  "United Kingdom - GB",
  "United States - US",
  "Vietnam - VN",
]

export const realtime_categories = [
  'b - Business', //Business
  'e - Entertainment', //Entertainment
  'm - Health', //Health,
  't - Sci/Tech', //Sci/Tech
  's - Sports', //Sports
  'h - Top stories', //Top stories
]

export default endpoints